export var tab1Data = {
	"data": [
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "70",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "cdsfcfdfdef",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "fdrf",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "",
			"notEdiatable": false
		}],
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "69",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "",
			"notEdiatable": false
		}],
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "68",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "",
			"notEdiatable": false
		}],
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "57",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "Testing",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "",
			"notEdiatable": false
		}],
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "5",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "Program",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "",
			"notEdiatable": false
		}],
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "4",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "Test Program",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "",
			"notEdiatable": false
		}],
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "3",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "Yes bank",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "",
			"notEdiatable": false
		}],
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "2",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "ABC Corporation",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "SRI UK",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "Casualty,Property,Cyber",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "56",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "41",
			"notEdiatable": false
		}],
		[{
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_ID",
			"value": "1",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "PROGRAM_NAME",
			"value": "Ford Motor Company",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "MASTER_INSURER",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "POLICY_TYPE",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "LOCAL_POLICIES",
			"value": "",
			"notEdiatable": false
		}, {
			"attributesMap": {},
			"columnSize": 0,
			"dbColumnName": "NETWORK_PARTNERS",
			"value": "",
			"notEdiatable": false
		}]
	],
	"headers": [{
		"attributesMap": {},
		"columnName": "PROGRAM_ID",
		"columnSize": 0,
		"notEdiatable": false
	}, {
		"attributesMap": {},
		"columnName": "PROGRAM_NAME",
		"columnSize": 0,
		"notEdiatable": false
	}, {
		"attributesMap": {},
		"columnName": "MASTER_INSURER",
		"columnSize": 0,
		"notEdiatable": false
	}, {
		"attributesMap": {},
		"columnName": "POLICY_TYPE",
		"columnSize": 0,
		"notEdiatable": false
	}, {
		"attributesMap": {},
		"columnName": "LOCAL_POLICIES",
		"columnSize": 0,
		"notEdiatable": false
	}, {
		"attributesMap": {},
		"columnName": "NETWORK_PARTNERS",
		"columnSize": 0,
		"notEdiatable": false
	}],
	"recordCount": 9,
	"statistics": {}
}